name 'mcanevet-raspbian_ua_netinst'
version '0.1.0'
dependency 'saz/locales'
dependency 'saz/timezone'
source 'https://github.com/mcanevet/puppet-raspbian_ua_netinst'
author 'Mickaël Canévet'
license 'Apache 2.0'
summary 'Puppet module for raspbian-ua-netinst'
description 'Puppet module to finish the installation of Toni Spets's raspbian-ua-netinst'
project_page 'https://github.com/mcanevet/puppet-raspbian_ua_netinst'
